#pragma once
#include <iostream>
#include <vector>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/glm.hpp>
#include <glm/gtx/string_cast.hpp>
#include <assimp/cimport.h>
#include <assimp/Importer.hpp>
#include "assimp/scene.h"
#include <assimp/postprocess.h>
#include <filesystem>